# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-01 10:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_auto_20170830_1532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='click_nums',
            field=models.IntegerField(default=0, verbose_name='\u70b9\u51fb\u6570\u91cf'),
        ),
    ]
